# Generated by Django 3.0 on 2021-01-14 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_auto_20210114_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='markedprice',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='sellingprice',
            field=models.PositiveIntegerField(),
        ),
    ]
