# Generated by Django 3.0 on 2021-01-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0004_auto_20210114_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='buylink',
            field=models.URLField(),
        ),
    ]
