# Generated by Django 3.0 on 2021-01-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0008_auto_20210114_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='launchdate',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
