# Generated by Django 3.0 on 2021-01-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0010_auto_20210116_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='sellingprice',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
