# Generated by Django 3.0 on 2021-01-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0012_auto_20210116_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='qualification',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
