# Generated by Django 3.0 on 2021-01-24 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0013_auto_20210116_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='indexsample',
            field=models.FileField(blank=True, upload_to='bookindex/'),
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ManyToManyField(to='bookapp.Publisher'),
        ),
    ]
