# Generated by Django 3.0 on 2021-01-26 15:03

from django.db import migrations, models
import django_backblaze_b2.storage


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0015_auto_20210126_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='coverphoto',
            field=models.ImageField(storage=django_backblaze_b2.storage.BackblazeB2Storage, upload_to='coverphoto/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='indexsample',
            field=models.FileField(blank=True, storage=django_backblaze_b2.storage.BackblazeB2Storage, upload_to='bookindex/'),
        ),
    ]
