# Generated by Django 3.0 on 2021-01-27 13:24

from django.db import migrations, models
import django_backblaze_b2.storage


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0017_auto_20210127_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='coverphoto',
            field=models.ImageField(storage=django_backblaze_b2.storage.BackblazeB2Storage, upload_to='coverphoto'),
        ),
        migrations.AlterField(
            model_name='book',
            name='indexsample',
            field=models.FileField(blank=True, storage=django_backblaze_b2.storage.BackblazeB2Storage, upload_to='bookindex'),
        ),
    ]
