# Generated by Django 3.0 on 2021-01-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0018_auto_20210127_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='coverphoto',
            field=models.ImageField(upload_to='coverphoto'),
        ),
        migrations.AlterField(
            model_name='book',
            name='indexsample',
            field=models.FileField(blank=True, upload_to='bookindex'),
        ),
    ]
