# Generated by Django 3.0 on 2021-01-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0019_auto_20210127_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='newarrival',
            field=models.BooleanField(default=False),
        ),
    ]
