# Generated by Django 3.0 on 2021-01-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0020_book_newarrival'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='newarrival',
        ),
        migrations.AddField(
            model_name='book',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
